name: Security scanner

on: [push, pull_request]

jobs:
  security:
    name: Local PHP Security Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "testing"

      - name: PHP Security Checker
        run: echo "PoC"

